.circleci/config.yml, .eslintrc.js, examples/basic.tsx, package.json, src/Filler.tsx, src/List.tsx, src/index.ts, src/util.ts, tests/index.test.js
Adjust exist [algorithm](https://github.com/react-component/tree/blob/perf-legacy/src/VirtualList/List.jsx) to support basic virtual scroll.
* Use `ref` to measure item height firstly.
* Downgrade to `findDOMNode` if not a real DOM element.
=> feat: Support basic virtual scroll

examples/animate.tsx, src/List.tsx, src/utils/itemUtil.ts, tests/scroll.test.js
用于支持 “虚拟列表” 与 “真实列表” 间切换时的滚动坐标重定位。
=> feat: Support switch between virtual & raw list

src/Filler.tsx, src/List.tsx
We set `overflow: visible` to keep the content display which not working on Firefox. Adjust logic to the `disabled` instead.
=> fix: Should keep count when `disabled`

src/List.tsx, tests/props.test.js
`rc-tree` something tree node not provides `key`, we use `pos` instead.
=> feat: `itemKey` support function

src/List.tsx, src/utils/algorithmUtil.ts, tests/util.test.js
Diff algorithm should match only 1 item diff instead of multiple content change.
=> fix: Only do align with 1 items

.eslintrc.js, examples/basic.tsx, src/List.tsx, tests/list.test.js, tests/scroll.test.js, tests/util.test.js, tests/utils/domHook.js
In rc-select, we should support open to scroll to the active item:
```jsx
listRef.current.scrollTo({ index: 233, align: 'auto' });
```
Support `align`:
* auto
* top
* bottom
=> feat: Support `scrollTo` item index

.circleci/config.yml, .eslintrc.js, package.json, src/List.tsx, src/utils/itemUtil.ts, tests/scroll.test.js
fix https://github.com/ant-design/ant-design/issues/21721
=> fix: Scroll to with SCU

.prettierrc, src/List.tsx, src/utils/itemUtil.ts, tests/list.test.js
ref https://github.com/ant-design/ant-design/issues/21722
=> feat: support disable `virtual`

examples/basic.tsx, src/List.tsx, src/hooks/useHeights.tsx, src/hooks/useScrollTo.tsx, src/utils/CacheMap.ts
Firefox 下 Map 的查询命中失败性能下降约 `~0.3 ns`。10w 条数据量累计下来会有接近 `20 ~ 30 ms` 的卡顿，倒是 object 没有这个神奇的问题，推测是内部实现 Map 的 key 需要遍历查询有关。Chrome 下会损失 1~2 ms 的渲染性能，问题不大。换了。
resolve https://github.com/ant-design/ant-design/pull/26278
=> Use object as map

src/hooks/useScrollTo.tsx
测试中直接跑 runAllTimer 没有时机变更高度，测试没法写有点蛋疼。这个 fix 主要逻辑就是等 3 帧，只要容器高度出现了就设置。反之放弃。
fix https://github.com/ant-design/ant-design/issues/26374
=> fix: Skip scroll when container not ready

src/List.tsx, src/hooks/useFrameWheel.ts, src/utils/isFirefox.ts, tests/scroll-Firefox.test.js
resolve https://github.com/ant-design/ant-design/issues/26372
Firefox 的鼠标滚动触发的 wheel 事件 `deltaY` 会比触摸板小很多。导致滚动看起来只有一小段距离，加一个 patch 来监听 FF 事件，如果发现 wheel 和 滚轮 事件数值相同（说明用的是鼠标），则添加一个倍数来滚动。
自己这边测了一下，FF 鼠标滚动和滚屏大概差 8 ~ 11 倍之间
=> fix: Add patch fix for firefox mouse wheel

examples/animate.tsx, src/List.tsx, src/hooks/useMobileTouchMove.ts
1. replace useEffect with useLayoutEffect
✅ Closes: [#27006](https://github.com/ant-design/ant-design/issues/27006)
=> fix: 🐛 error in React 17

examples/switch.tsx, src/ScrollBar.tsx
resolve https://github.com/ant-design/ant-design/issues/30175
=> feat: Add one more className

package.json
The api `useLayoutEffect` depends on `rc-util` 5.15.0 version or later.
=> fix:  fix dependencies `rc-util` version

src/ScrollBar.tsx
Fixes error "Cannot read property removeEventListener of null" 
Related issues: 
close https://github.com/react-component/virtual-list/pull/163
close https://github.com/ant-design/ant-design/issues/34816
close https://github.com/ant-design/ant-design/issues/35221
close #178
=> fix: check null ref before removeEventListener

examples/horizontal-scroll.tsx, src/Filler.tsx, src/List.tsx, src/hooks/useChildren.tsx, src/interface.ts, tests/scrollWidth.test.tsx
* Filler 设置宽度为 `scrollWidth` 时会导致 `sticky: right` 无效。把它挪到里面的 Item 上做 margin 偏移以支持 sticky。
* 支持 `extraRender` 将额外内容添加至滚动容器中。
=> refactor: replace scroll logic with inner width

examples/horizontal-scroll.tsx, src/Filler.tsx, src/List.tsx, tests/scrollWidth.test.tsx
水平滚动是不会触发原生 scroll 事件的，我们这边添加一个模拟事件。
=> feat: support `onVirtualScroll` event

examples/horizontal-scroll.tsx, src/List.tsx, src/interface.ts, tests/scrollWidth.test.tsx
=> feat: support render get size

examples/horizontal-scroll.tsx, src/List.tsx, src/hooks/useGetSize.ts, src/interface.ts, src/utils/CacheMap.ts
优化 `getSize` 速度，重复读取时会复用先前生成的缓存。
=> refactor: opt getSize speed

examples/horizontal-scroll.tsx, src/ScrollBar.tsx
拖拽时会不断更新真正的高度数据，这使得进行时的总高度是不断变化的。在闭包中这个数据不会变，用 ref 提取一下。
=> fix: scrollbar closure

src/List.tsx, tests/scroll.test.js
max `end` should be `data.length - 1`
=> fix: end should not exceed len

src/hooks/useFrameWheel.ts, tests/scrollWidth.test.tsx
resolve https://github.com/ant-design/ant-design/issues/44775
=> chore: shift wheel trigger horizontal scroll

src/List.tsx, tests/scrollWidth.test.tsx
fix https://github.com/ant-design/ant-design/issues/44889
=> fix: scrollLeft should keep in sync when width changed

examples/basic.tsx, src/List.tsx, src/hooks/useHeights.tsx, src/hooks/useScrollTo.tsx, tests/scroll.test.js
ref https://github.com/react-component/virtual-list/pull/226/files#r1329877475
使用 `useEffectLayout` 进行滚动，从而跳过闪屏阶段 。
resolve: https://github.com/ant-design/ant-design/issues/44100
=> fix: `scrollTo` flash

README.md, src/List.tsx, src/ScrollBar.tsx, tests/scroll.test.js
=> feat: support scrollbar style

src/List.tsx, tests/scroll.test.js
v4 中的下拉框在动画启动时通过 `transform` 设置 `scaleY: 0`，导致 `onResize` 事件触发时设置容器高度为 `0` 而让滚动条 thumb 高度坍缩成 `0`。
而 v5 中，动画是从 `scaleY: 0.8` 开始。倒是 thumb 高度虽然不符合预期，但是仍然可以见到。
其中，不同 antd 版本的滚动条其实都是可以正常滚动。这个计算只影响 thumb 展示高度。
fix https://github.com/ant-design/ant-design/issues/45078
=> fix: scrollbar invisible

src/hooks/useScrollTo.tsx
resolve https://github.com/ant-design/ant-design/issues/45628
正常情况下直接设置和 func 设置应该是等价的：
```tsx
const [val, setVal] = useState(0);
useLayoutEffect(() => {
if (val < 3) {
setVal(val + 1); // Should same as: setVal(v => v + 1);
}
}, [val]);
```
但是在 React StrictMode 中，回放出现了重叠：
```tsx
useLayoutEffect(() => {
if (val < 3) {
console.log('effect!');
setVal(v => {
console.log('🔥 state update!');
return v + 1;
});
}
}, [val]);
```
`useLayoutEffect` 不会触发的情况下，`setVal` 会被调用然后认为可以触发 `useLayoutEffect` 导致无限循环：
这个行为直接写 codesandbox 不会出现：
https://codesandbox.io/s/vigorous-sea-vsr2ty?file=/src/App.tsx
差异在于死循环的 case 中多出了 batchUpdate：
推测是复杂场景下，React 会将一批操作 Batch 掉。但是对于 StrictMode 下，effect 会多次执行确保开发者做了清理，导致 setState(action) 在 effect 周期外执行。从而导致了 update 触发了 effect 需要执行，而该 effect 又关联了 update 被回放导致死循环。
目前看起来，这是一个 …
=> fix: dead loop in strict mode

src/List.tsx, src/ScrollBar.tsx, src/utils/scrollbarUtil.ts, tests/scroll.test.js
1、使滚动条的长度与真实的滚动条长度差不多，原来的计算方式不对
这里滚动体宽度太短了，与非 virtual 模式下差距太大
2、scrollWidth > size.width 时才显示 horizontal 滚动条，所以内部 canScroll 没用了
=> fix: modify scroll bar size

src/List.tsx, tests/scroll.test.js, tests/scrollWidth.test.tsx
复现步骤：
1. 修改 examples 中 height 例子，将 data 数据调整为 10 条，目前能够滚动，但是没有滚动条
2. 调整逻辑后滚动条正常显示
close #243
close https://github.com/ant-design/ant-design/issues/45935
=> fix: adjust inVirtual logic(#227)

src/List.tsx, tests/scrollWidth.test.tsx
scrollWidth 发生改变，onVirtualScroll 应该触发，这样能得到最新的正确的偏移值
=> fix: onVirtualScroll should be triggered when scrollWidth changed

src/List.tsx, src/hooks/useChildren.tsx, src/interface.ts, tests/props.test.js
renderFunction 直接能获取 scrollLeft，Table 列虚拟能直接使用，而不需要使用其它方式获取
=> feat: add offsetX to renderFn

src/hooks/useMobileTouchMove.ts
有小数会导致 rc-table 会进入这段代码。
因为从 dom 获取 scrollLeft(target.scrollLeft) 总是整数，如果传入的有小数，会进入这段 hack 代码，会出现问题
=> fix: Math.floor touch offset

src/List.tsx, src/ScrollBar.tsx, src/hooks/useMobileTouchMove.ts
=> fix: resolve passive warning

src/hooks/useScrollDrag.ts, tests/scroll.test.js
fix https://github.com/ant-design/ant-design/issues/53163
=> fix: right click should not trigger drag
