react-component/virtual-list

examples/no-virtual.tsx
src/List.tsx
src/utils/algorithmUtil.ts
tests/diff.test.js
tests/scroll.test.js
tests/util.test.js
tests/utils/domHook.js

chore: Full test coverage

---

src/Item.tsx
src/List.tsx
src/hooks/useChildren.tsx
src/hooks/useFrameWheel.ts
src/hooks/useHeights.tsx
tests/list.test.js
tests/mock.test.js
tests/props.test.js
tests/scroll.test.js

FF 在大页面下，还是会有性能问题。撤销 Map 的变更。改由部分内容用 frame 来实现。
ref https://github.com/ant-design/ant-design/pull/26282

refactor: Use frame of scroll

---

examples/basic.tsx
src/List.tsx
tests/scroll.test.js

fix https://github.com/ant-design/ant-design/issues/26352

fix: failed target of onScroll

---

src/List.tsx
src/ScrollBar.tsx
src/hooks/useMobileTouchMove.ts
tests/touch.test.js

resolve https://github.com/ant-design/ant-design/issues/26480

fix: Touch event should work on list

---

src/Filler.tsx
src/hooks/useHeights.tsx
tests/list.test.js

fix https://github.com/ant-design/ant-design/issues/26586

fix: Item render will also collect heights

---

examples/basic.tsx
src/List.tsx
src/hooks/useScrollTo.tsx

`scrollTo` support `offset`.
https://virtual-list-git-offset.react-component.vercel.app/iframe.html?id=rc-virtual-list--basic

feat: support offset

---

.eslintrc.js
examples/basic.tsx
examples/no-virtual.tsx
examples/switch.tsx
src/Filler.tsx
src/List.tsx
src/ScrollBar.tsx
src/hooks/useHeights.tsx
src/hooks/useScrollTo.tsx
tests/scroll.test.js

resolve https://github.com/ant-design/ant-design/issues/27151

refactor: Virtual always use fake scroll bar

---

src/ScrollBar.tsx
tests/scroll.test.js

fix https://github.com/ant-design/ant-design/issues/27282

fix: divisor cannot be 0

---

tests/util.test.js

Hello, my name is Junior. I have one suggest for you: "Use const, for better syntax"
have a nice day :+1:

Update, set const for findListDiffIndex.

---

examples/basic.tsx
src/List.tsx
src/hooks/useScrollTo.tsx
tests/scroll.test.js

resolve https://github.com/ant-design/ant-design/issues/28245

fix: Should not crash when item remove by scroll

---

src/List.tsx
tests/scroll.test.js

fix https://github.com/ant-design/ant-design/issues/28468

fix: should not out of range

---

src/List.tsx
tests/scroll.test.js

fix https://github.com/ant-design/ant-design/issues/28861
fix https://github.com/react-component/virtual-list/issues/102

fix: scroll issue

---

src/List.tsx
src/hooks/useMobileTouchMove.ts

Cannot read property removeEventListener of null

---

src/List.tsx
tests/scroll.test.js

fix https://github.com/ant-design/ant-design/issues/37986

fix: Cut content when size exceed

---

package.json
src/hooks/useScrollTo.tsx

fix https://github.com/ant-design/ant-design/issues/39343

fix: scroll top logic

---

src/Filler.tsx
src/List.tsx
tests/list.test.js

ref https://github.com/ant-design/ant-design/issues/39199

feat: Add innerProps

---

src/index.ts

fix: repair startup warning

---

src/List.tsx
src/ScrollBar.tsx
tests/scroll.test.js

- fix https://github.com/ant-design/ant-design/issues/42331

feat: add List ScrollBar direction

---

docs/demo/horizontal-scroll.md
examples/horizontal-scroll.tsx
package.json
src/Filler.tsx
src/List.tsx
src/ScrollBar.tsx
tests/list.test.js
tests/scroll.test.js
tests/scrollWidth.test.tsx

Pick part of https://github.com/react-component/virtual-list/pull/209

feat: scrollWidth support

---

examples/horizontal-scroll.tsx

type(examples): optimize style type

---

src/List.tsx
src/hooks/useScrollTo.tsx
tests/scrollWidth.test.tsx

feat: scrollTo support { left }

---

package.json

close https://github.com/ant-design/ant-design/issues/44271

fix: fix depds

---

src/List.tsx

fix: code style improve

---

src/List.tsx
tests/scrollWidth.test.tsx

https://github.com/react-component/virtual-list/pull/262#discussion_r1569866309

chore: remove maxScrollWidth and maxScrollHeight

---

src/List.tsx
src/hooks/useFrameWheel.ts
src/hooks/useMobileTouchMove.ts
src/hooks/useOriginScroll.ts
tests/scrollWidth.test.tsx

fix https://github.com/ant-design/ant-design/issues/47113

feat: support touch horizontal scroll

---

src/ScrollBar.tsx
tests/scrollWidth.test.tsx

fix https://github.com/ant-design/ant-design/issues/49539

fix: scale scroll
